---
name: CI
on:
  pull_request:
  push:
    branches: [master]
jobs:
  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sandbar-js
    steps:
      - uses: actions/checkout@v2
        with:
          path: sandbar-js
      - uses: actions/checkout@v2
        with:
          repository: googleapis/googleapis
          path: googleapis
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install modules
        run: pnpm i
      - name: Run codegen
        run: pnpm run codegen
      - name: Run tests
        run: pnpm test
